# Generated by Django 5.2.8 on 2026-02-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_chat_options_alter_message_options_and_more'),
        ('jobs', '0004_remove_job_requirements_delete_requeriments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback do teste'),
        ),
        migrations.AddField(
            model_name='chat',
            name='recommended_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_chats', to='jobs.job', verbose_name='Curso recomendado'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='jobs.job'),
        ),
    ]
