# Generated by Django 5.2.8 on 2026-02-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_chat_feedback_chat_recommended_job_alter_chat_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do candidato'),
        ),
    ]
